# Generated by Django 5.0.6 on 2024-07-18 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertion',
            name='price',
        ),
        migrations.AddField(
            model_name='insertion',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='insertion_covers'),
        ),
        migrations.AddField(
            model_name='insertion',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insertion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
