# Generated by Django 5.0.6 on 2024-08-02 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='insertion',
            name='price',
        ),
        migrations.AddField(
            model_name='insertion',
            name='_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='insertion',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insertion',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insertion',
            name='cover_image',
            field=models.ImageField(default='covers/default.jpg', upload_to='covers'),
        ),
        migrations.AddField(
            model_name='insertion',
            name='host',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insertion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insertion',
            name='king_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insertion',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insertion',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insertion',
            name='max_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insertion',
            name='rules',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insertion',
            name='services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='insertion',
            name='single_beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insertion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('is_fixed_price', models.BooleanField(default=True, verbose_name='Prezzo fisso')),
                ('price_per_night', models.FloatField(default=0, verbose_name='Prezzo a notte (fisso)')),
                ('price_per_night_per_person', models.FloatField(blank=True, default=0, verbose_name='Prezzo a notte per persona (in caso di prezzo variabile)')),
                ('insertion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion.insertion')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guests', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insertion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion.insertion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
