# Generated by Django 5.0.6 on 2024-08-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0002_remove_insertion_id_remove_insertion_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='cover_image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='covers'),
        ),
    ]
