# Generated by Django 5.0.6 on 2024-08-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0003_alter_insertion_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insertion',
            old_name='_metadata',
            new_name='metadata',
        ),
    ]
