# Generated by Django 5.0.6 on 2024-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0003_alter_insertion_host_alter_insertion_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
