# Generated by Django 5.0.6 on 2024-08-05 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0004_rename__metadata_insertion_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insertion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion.insertion')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion.reservation')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
