# Generated by Django 5.0.6 on 2024-07-18 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0004_alter_insertion_latitude_alter_insertion_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertion',
            name='_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='insertion',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='insertion',
            name='rules',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('insertion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insertion.insertion')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
    ]
