# Generated by Django 5.0.6 on 2024-07-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0007_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='max_guests',
        ),
        migrations.AddField(
            model_name='insertion',
            name='max_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='insertion',
            name='rules',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(),
        ),
    ]
