# Generated by Django 5.0.6 on 2024-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0008_remove_availability_max_guests_insertion_max_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertion',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
