# Generated by Django 5.0.6 on 2024-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0009_insertion_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertion',
            name='rules',
            field=models.TextField(),
        ),
    ]
