# Generated by Django 5.0.6 on 2024-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insertion', '0010_alter_insertion_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertion',
            name='features',
        ),
        migrations.AddField(
            model_name='insertion',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insertion',
            name='bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insertion',
            name='king_beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insertion',
            name='services',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='insertion',
            name='single_beds',
            field=models.IntegerField(default=1),
        ),
    ]
