services = [
    {'name': 'Wi-Fi', 'icon': 'wifi-outline', 'id': 1},
    {'name': 'Giardino privato', 'icon': 'flower-outline', 'id': 2},
    {'name': 'Piscina', 'icon': 'water-outline', 'id': 3},
    {'name': 'Cucina', 'icon': 'wine-outline', 'id': 4},
    {'name': 'TV', 'icon': 'tv-outline', 'id': 5},
    {'name': 'Aria condizionata', 'icon': 'snow-outline', 'id': 6},
    {'name': 'Riscaldamento', 'icon': 'thermometer-outline', 'id': 7},
    {'name': 'Lavatrice', 'icon': 'cube-outline', 'id': 8},
    {'name': 'Asciugatrice', 'icon': 'cube-outline', 'id': 9},
    {'name': 'Lavastoviglie', 'icon': 'cube-outline', 'id': 10},
    {'name': 'Parcheggio', 'icon': 'car-outline', 'id': 11},
    {'name': 'Animali ammessi', 'icon': 'paw-outline', 'id': 12},
    {'name': 'Colazione inclusa', 'icon': 'fast-food-outline', 'id': 13},
    {'name': 'Vista mare', 'icon': 'boat-outline', 'id': 14},
    {'name': 'Rilevatore di fumo', 'icon': 'alert-circle-outline', 'id': 15},
    {'name': 'Asciugacapelli', 'icon': 'cube-outline', 'id': 16},
    {'name': 'Bagno privato', 'icon': 'eye-off-outline', 'id': 17},
]