# Generated by Django 5.0.6 on 2024-07-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='iban',
            field=models.CharField(blank=True, max_length=27),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tax_code',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
