# Generated by Django 5.0.6 on 2024-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_birth_date_alter_customuser_iban_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='iban',
            field=models.CharField(max_length=27, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default='profile_pics/default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tax_code',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
